/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgenteRouteImport } from './routes/_authenticated/agente'
import { Route as AuthenticatedBilleteraRouteImport } from './routes/_authenticated/billetera'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnviarRouteImport } from './routes/_authenticated/enviar'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedSoporteRouteImport } from './routes/_authenticated/soporte'
import { Route as AuthenticatedTarjetaRouteImport } from './routes/_authenticated/tarjeta'
import { Route as AuthenticatedTransferenciaIdRouteImport } from './routes/_authenticated/transferencia.$id'
import { Route as ApiPublicBazikPayoutRouteImport } from './routes/api/public/bazik/payout'
import { Route as ApiPublicBazikTopupRouteImport } from './routes/api/public/bazik/topup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenteRoute = AuthenticatedAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBilleteraRoute = AuthenticatedBilleteraRouteImport.update({
  id: '/billetera',
  path: '/billetera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviarRoute = AuthenticatedEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoporteRoute = AuthenticatedSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarjetaRoute = AuthenticatedTarjetaRouteImport.update({
  id: '/tarjeta',
  path: '/tarjeta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferenciaIdRoute =
  AuthenticatedTransferenciaIdRouteImport.update({
    id: '/transferencia/$id',
    path: '/transferencia/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBazikPayoutRoute = ApiPublicBazikPayoutRouteImport.update({
  id: '/api/public/bazik/payout',
  path: '/api/public/bazik/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBazikTopupRoute = ApiPublicBazikTopupRouteImport.update({
  id: '/api/public/bazik/topup',
  path: '/api/public/bazik/topup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/billetera': typeof AuthenticatedBilleteraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/tarjeta': typeof AuthenticatedTarjetaRoute
  '/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/bazik/topup': typeof ApiPublicBazikTopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/billetera': typeof AuthenticatedBilleteraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/tarjeta': typeof AuthenticatedTarjetaRoute
  '/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/bazik/topup': typeof ApiPublicBazikTopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agente': typeof AuthenticatedAgenteRoute
  '/_authenticated/billetera': typeof AuthenticatedBilleteraRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enviar': typeof AuthenticatedEnviarRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/soporte': typeof AuthenticatedSoporteRoute
  '/_authenticated/tarjeta': typeof AuthenticatedTarjetaRoute
  '/_authenticated/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/bazik/topup': typeof ApiPublicBazikTopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agente'
    | '/billetera'
    | '/dashboard'
    | '/enviar'
    | '/historial'
    | '/perfil'
    | '/soporte'
    | '/tarjeta'
    | '/transferencia/$id'
    | '/api/public/bazik/payout'
    | '/api/public/bazik/topup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agente'
    | '/billetera'
    | '/dashboard'
    | '/enviar'
    | '/historial'
    | '/perfil'
    | '/soporte'
    | '/tarjeta'
    | '/transferencia/$id'
    | '/api/public/bazik/payout'
    | '/api/public/bazik/topup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agente'
    | '/_authenticated/billetera'
    | '/_authenticated/dashboard'
    | '/_authenticated/enviar'
    | '/_authenticated/historial'
    | '/_authenticated/perfil'
    | '/_authenticated/soporte'
    | '/_authenticated/tarjeta'
    | '/_authenticated/transferencia/$id'
    | '/api/public/bazik/payout'
    | '/api/public/bazik/topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBazikPayoutRoute: typeof ApiPublicBazikPayoutRoute
  ApiPublicBazikTopupRoute: typeof ApiPublicBazikTopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agente': {
      id: '/_authenticated/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AuthenticatedAgenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billetera': {
      id: '/_authenticated/billetera'
      path: '/billetera'
      fullPath: '/billetera'
      preLoaderRoute: typeof AuthenticatedBilleteraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviar': {
      id: '/_authenticated/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof AuthenticatedEnviarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soporte': {
      id: '/_authenticated/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AuthenticatedSoporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarjeta': {
      id: '/_authenticated/tarjeta'
      path: '/tarjeta'
      fullPath: '/tarjeta'
      preLoaderRoute: typeof AuthenticatedTarjetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencia/$id': {
      id: '/_authenticated/transferencia/$id'
      path: '/transferencia/$id'
      fullPath: '/transferencia/$id'
      preLoaderRoute: typeof AuthenticatedTransferenciaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bazik/payout': {
      id: '/api/public/bazik/payout'
      path: '/api/public/bazik/payout'
      fullPath: '/api/public/bazik/payout'
      preLoaderRoute: typeof ApiPublicBazikPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bazik/topup': {
      id: '/api/public/bazik/topup'
      path: '/api/public/bazik/topup'
      fullPath: '/api/public/bazik/topup'
      preLoaderRoute: typeof ApiPublicBazikTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgenteRoute: typeof AuthenticatedAgenteRoute
  AuthenticatedBilleteraRoute: typeof AuthenticatedBilleteraRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnviarRoute: typeof AuthenticatedEnviarRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSoporteRoute: typeof AuthenticatedSoporteRoute
  AuthenticatedTarjetaRoute: typeof AuthenticatedTarjetaRoute
  AuthenticatedTransferenciaIdRoute: typeof AuthenticatedTransferenciaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgenteRoute: AuthenticatedAgenteRoute,
  AuthenticatedBilleteraRoute: AuthenticatedBilleteraRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnviarRoute: AuthenticatedEnviarRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSoporteRoute: AuthenticatedSoporteRoute,
  AuthenticatedTarjetaRoute: AuthenticatedTarjetaRoute,
  AuthenticatedTransferenciaIdRoute: AuthenticatedTransferenciaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBazikPayoutRoute: ApiPublicBazikPayoutRoute,
  ApiPublicBazikTopupRoute: ApiPublicBazikTopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
