/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoEnviarDineroRouteImport } from './routes/como-enviar-dinero'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EnviarDineroAHaitiRouteImport } from './routes/enviar-dinero-a-haiti'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MoncashRouteImport } from './routes/moncash'
import { Route as NatcashRouteImport } from './routes/natcash'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RestablecerPasswordRouteImport } from './routes/restablecer-password'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as TarifasRouteImport } from './routes/tarifas'
import { Route as TraderRouteImport } from './routes/trader'
import { Route as UsaToHaitiRouteImport } from './routes/usa-to-haiti'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangComoEnviarDineroRouteImport } from './routes/$lang/como-enviar-dinero'
import { Route as LangContactoRouteImport } from './routes/$lang/contacto'
import { Route as LangEnviarDineroAHaitiRouteImport } from './routes/$lang/enviar-dinero-a-haiti'
import { Route as LangMoncashRouteImport } from './routes/$lang/moncash'
import { Route as LangNatcashRouteImport } from './routes/$lang/natcash'
import { Route as LangSobreNosotrosRouteImport } from './routes/$lang/sobre-nosotros'
import { Route as LangTarifasRouteImport } from './routes/$lang/tarifas'
import { Route as LangTraderRouteImport } from './routes/$lang/trader'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgenteRouteImport } from './routes/_authenticated/agente'
import { Route as AuthenticatedCriptoRouteImport } from './routes/_authenticated/cripto'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnviarRouteImport } from './routes/_authenticated/enviar'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRecargasRouteImport } from './routes/_authenticated/recargas'
import { Route as AuthenticatedSoporteRouteImport } from './routes/_authenticated/soporte'
import { Route as AuthenticatedTransferenciaIdRouteImport } from './routes/_authenticated/transferencia.$id'
import { Route as ApiPublicAuthWelcomeRouteImport } from './routes/api/public/auth/welcome'
import { Route as ApiPublicBazikPayoutRouteImport } from './routes/api/public/bazik/payout'
import { Route as ApiPublicDingconnectWebhookRouteImport } from './routes/api/public/dingconnect/webhook'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'
import { Route as ApiPublicSecurityAlertRouteImport } from './routes/api/public/security/alert'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoEnviarDineroRoute = ComoEnviarDineroRouteImport.update({
  id: '/como-enviar-dinero',
  path: '/como-enviar-dinero',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarDineroAHaitiRoute = EnviarDineroAHaitiRouteImport.update({
  id: '/enviar-dinero-a-haiti',
  path: '/enviar-dinero-a-haiti',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MoncashRoute = MoncashRouteImport.update({
  id: '/moncash',
  path: '/moncash',
  getParentRoute: () => rootRouteImport,
} as any)
const NatcashRoute = NatcashRouteImport.update({
  id: '/natcash',
  path: '/natcash',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerPasswordRoute = RestablecerPasswordRouteImport.update({
  id: '/restablecer-password',
  path: '/restablecer-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifasRoute = TarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => rootRouteImport,
} as any)
const TraderRoute = TraderRouteImport.update({
  id: '/trader',
  path: '/trader',
  getParentRoute: () => rootRouteImport,
} as any)
const UsaToHaitiRoute = UsaToHaitiRouteImport.update({
  id: '/usa-to-haiti',
  path: '/usa-to-haiti',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangComoEnviarDineroRoute = LangComoEnviarDineroRouteImport.update({
  id: '/$lang/como-enviar-dinero',
  path: '/$lang/como-enviar-dinero',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactoRoute = LangContactoRouteImport.update({
  id: '/$lang/contacto',
  path: '/$lang/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LangEnviarDineroAHaitiRoute = LangEnviarDineroAHaitiRouteImport.update({
  id: '/$lang/enviar-dinero-a-haiti',
  path: '/$lang/enviar-dinero-a-haiti',
  getParentRoute: () => rootRouteImport,
} as any)
const LangMoncashRoute = LangMoncashRouteImport.update({
  id: '/$lang/moncash',
  path: '/$lang/moncash',
  getParentRoute: () => rootRouteImport,
} as any)
const LangNatcashRoute = LangNatcashRouteImport.update({
  id: '/$lang/natcash',
  path: '/$lang/natcash',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSobreNosotrosRoute = LangSobreNosotrosRouteImport.update({
  id: '/$lang/sobre-nosotros',
  path: '/$lang/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTarifasRoute = LangTarifasRouteImport.update({
  id: '/$lang/tarifas',
  path: '/$lang/tarifas',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTraderRoute = LangTraderRouteImport.update({
  id: '/$lang/trader',
  path: '/$lang/trader',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenteRoute = AuthenticatedAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriptoRoute = AuthenticatedCriptoRouteImport.update({
  id: '/cripto',
  path: '/cripto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviarRoute = AuthenticatedEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecargasRoute = AuthenticatedRecargasRouteImport.update({
  id: '/recargas',
  path: '/recargas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoporteRoute = AuthenticatedSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferenciaIdRoute =
  AuthenticatedTransferenciaIdRouteImport.update({
    id: '/transferencia/$id',
    path: '/transferencia/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthWelcomeRoute = ApiPublicAuthWelcomeRouteImport.update({
  id: '/api/public/auth/welcome',
  path: '/api/public/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBazikPayoutRoute = ApiPublicBazikPayoutRouteImport.update({
  id: '/api/public/bazik/payout',
  path: '/api/public/bazik/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDingconnectWebhookRoute =
  ApiPublicDingconnectWebhookRouteImport.update({
    id: '/api/public/dingconnect/webhook',
    path: '/api/public/dingconnect/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSecurityAlertRoute = ApiPublicSecurityAlertRouteImport.update({
  id: '/api/public/security/alert',
  path: '/api/public/security/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-enviar-dinero': typeof ComoEnviarDineroRoute
  '/contacto': typeof ContactoRoute
  '/enviar-dinero-a-haiti': typeof EnviarDineroAHaitiRoute
  '/faq': typeof FaqRoute
  '/moncash': typeof MoncashRoute
  '/natcash': typeof NatcashRoute
  '/privacidad': typeof PrivacidadRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tarifas': typeof TarifasRoute
  '/trader': typeof TraderRoute
  '/usa-to-haiti': typeof UsaToHaitiRoute
  '/$lang/como-enviar-dinero': typeof LangComoEnviarDineroRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/enviar-dinero-a-haiti': typeof LangEnviarDineroAHaitiRoute
  '/$lang/moncash': typeof LangMoncashRoute
  '/$lang/natcash': typeof LangNatcashRoute
  '/$lang/sobre-nosotros': typeof LangSobreNosotrosRoute
  '/$lang/tarifas': typeof LangTarifasRoute
  '/$lang/trader': typeof LangTraderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/cripto': typeof AuthenticatedCriptoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recargas': typeof AuthenticatedRecargasRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/$lang/': typeof LangIndexRoute
  '/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/auth/welcome': typeof ApiPublicAuthWelcomeRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/dingconnect/webhook': typeof ApiPublicDingconnectWebhookRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/security/alert': typeof ApiPublicSecurityAlertRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-enviar-dinero': typeof ComoEnviarDineroRoute
  '/contacto': typeof ContactoRoute
  '/enviar-dinero-a-haiti': typeof EnviarDineroAHaitiRoute
  '/faq': typeof FaqRoute
  '/moncash': typeof MoncashRoute
  '/natcash': typeof NatcashRoute
  '/privacidad': typeof PrivacidadRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tarifas': typeof TarifasRoute
  '/trader': typeof TraderRoute
  '/usa-to-haiti': typeof UsaToHaitiRoute
  '/$lang/como-enviar-dinero': typeof LangComoEnviarDineroRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/enviar-dinero-a-haiti': typeof LangEnviarDineroAHaitiRoute
  '/$lang/moncash': typeof LangMoncashRoute
  '/$lang/natcash': typeof LangNatcashRoute
  '/$lang/sobre-nosotros': typeof LangSobreNosotrosRoute
  '/$lang/tarifas': typeof LangTarifasRoute
  '/$lang/trader': typeof LangTraderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agente': typeof AuthenticatedAgenteRoute
  '/cripto': typeof AuthenticatedCriptoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/recargas': typeof AuthenticatedRecargasRoute
  '/soporte': typeof AuthenticatedSoporteRoute
  '/$lang': typeof LangIndexRoute
  '/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/auth/welcome': typeof ApiPublicAuthWelcomeRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/dingconnect/webhook': typeof ApiPublicDingconnectWebhookRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/security/alert': typeof ApiPublicSecurityAlertRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-enviar-dinero': typeof ComoEnviarDineroRoute
  '/contacto': typeof ContactoRoute
  '/enviar-dinero-a-haiti': typeof EnviarDineroAHaitiRoute
  '/faq': typeof FaqRoute
  '/moncash': typeof MoncashRoute
  '/natcash': typeof NatcashRoute
  '/privacidad': typeof PrivacidadRoute
  '/restablecer-password': typeof RestablecerPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tarifas': typeof TarifasRoute
  '/trader': typeof TraderRoute
  '/usa-to-haiti': typeof UsaToHaitiRoute
  '/$lang/como-enviar-dinero': typeof LangComoEnviarDineroRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/enviar-dinero-a-haiti': typeof LangEnviarDineroAHaitiRoute
  '/$lang/moncash': typeof LangMoncashRoute
  '/$lang/natcash': typeof LangNatcashRoute
  '/$lang/sobre-nosotros': typeof LangSobreNosotrosRoute
  '/$lang/tarifas': typeof LangTarifasRoute
  '/$lang/trader': typeof LangTraderRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agente': typeof AuthenticatedAgenteRoute
  '/_authenticated/cripto': typeof AuthenticatedCriptoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enviar': typeof AuthenticatedEnviarRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/recargas': typeof AuthenticatedRecargasRoute
  '/_authenticated/soporte': typeof AuthenticatedSoporteRoute
  '/$lang/': typeof LangIndexRoute
  '/_authenticated/transferencia/$id': typeof AuthenticatedTransferenciaIdRoute
  '/api/public/auth/welcome': typeof ApiPublicAuthWelcomeRoute
  '/api/public/bazik/payout': typeof ApiPublicBazikPayoutRoute
  '/api/public/dingconnect/webhook': typeof ApiPublicDingconnectWebhookRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/security/alert': typeof ApiPublicSecurityAlertRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-enviar-dinero'
    | '/contacto'
    | '/enviar-dinero-a-haiti'
    | '/faq'
    | '/moncash'
    | '/natcash'
    | '/privacidad'
    | '/restablecer-password'
    | '/sobre-nosotros'
    | '/tarifas'
    | '/trader'
    | '/usa-to-haiti'
    | '/$lang/como-enviar-dinero'
    | '/$lang/contacto'
    | '/$lang/enviar-dinero-a-haiti'
    | '/$lang/moncash'
    | '/$lang/natcash'
    | '/$lang/sobre-nosotros'
    | '/$lang/tarifas'
    | '/$lang/trader'
    | '/admin'
    | '/agente'
    | '/cripto'
    | '/dashboard'
    | '/enviar'
    | '/historial'
    | '/perfil'
    | '/recargas'
    | '/soporte'
    | '/$lang/'
    | '/transferencia/$id'
    | '/api/public/auth/welcome'
    | '/api/public/bazik/payout'
    | '/api/public/dingconnect/webhook'
    | '/api/public/mercadopago/webhook'
    | '/api/public/security/alert'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-enviar-dinero'
    | '/contacto'
    | '/enviar-dinero-a-haiti'
    | '/faq'
    | '/moncash'
    | '/natcash'
    | '/privacidad'
    | '/restablecer-password'
    | '/sobre-nosotros'
    | '/tarifas'
    | '/trader'
    | '/usa-to-haiti'
    | '/$lang/como-enviar-dinero'
    | '/$lang/contacto'
    | '/$lang/enviar-dinero-a-haiti'
    | '/$lang/moncash'
    | '/$lang/natcash'
    | '/$lang/sobre-nosotros'
    | '/$lang/tarifas'
    | '/$lang/trader'
    | '/admin'
    | '/agente'
    | '/cripto'
    | '/dashboard'
    | '/enviar'
    | '/historial'
    | '/perfil'
    | '/recargas'
    | '/soporte'
    | '/$lang'
    | '/transferencia/$id'
    | '/api/public/auth/welcome'
    | '/api/public/bazik/payout'
    | '/api/public/dingconnect/webhook'
    | '/api/public/mercadopago/webhook'
    | '/api/public/security/alert'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-enviar-dinero'
    | '/contacto'
    | '/enviar-dinero-a-haiti'
    | '/faq'
    | '/moncash'
    | '/natcash'
    | '/privacidad'
    | '/restablecer-password'
    | '/sobre-nosotros'
    | '/tarifas'
    | '/trader'
    | '/usa-to-haiti'
    | '/$lang/como-enviar-dinero'
    | '/$lang/contacto'
    | '/$lang/enviar-dinero-a-haiti'
    | '/$lang/moncash'
    | '/$lang/natcash'
    | '/$lang/sobre-nosotros'
    | '/$lang/tarifas'
    | '/$lang/trader'
    | '/_authenticated/admin'
    | '/_authenticated/agente'
    | '/_authenticated/cripto'
    | '/_authenticated/dashboard'
    | '/_authenticated/enviar'
    | '/_authenticated/historial'
    | '/_authenticated/perfil'
    | '/_authenticated/recargas'
    | '/_authenticated/soporte'
    | '/$lang/'
    | '/_authenticated/transferencia/$id'
    | '/api/public/auth/welcome'
    | '/api/public/bazik/payout'
    | '/api/public/dingconnect/webhook'
    | '/api/public/mercadopago/webhook'
    | '/api/public/security/alert'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoEnviarDineroRoute: typeof ComoEnviarDineroRoute
  ContactoRoute: typeof ContactoRoute
  EnviarDineroAHaitiRoute: typeof EnviarDineroAHaitiRoute
  FaqRoute: typeof FaqRoute
  MoncashRoute: typeof MoncashRoute
  NatcashRoute: typeof NatcashRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RestablecerPasswordRoute: typeof RestablecerPasswordRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TarifasRoute: typeof TarifasRoute
  TraderRoute: typeof TraderRoute
  UsaToHaitiRoute: typeof UsaToHaitiRoute
  LangComoEnviarDineroRoute: typeof LangComoEnviarDineroRoute
  LangContactoRoute: typeof LangContactoRoute
  LangEnviarDineroAHaitiRoute: typeof LangEnviarDineroAHaitiRoute
  LangMoncashRoute: typeof LangMoncashRoute
  LangNatcashRoute: typeof LangNatcashRoute
  LangSobreNosotrosRoute: typeof LangSobreNosotrosRoute
  LangTarifasRoute: typeof LangTarifasRoute
  LangTraderRoute: typeof LangTraderRoute
  LangIndexRoute: typeof LangIndexRoute
  ApiPublicAuthWelcomeRoute: typeof ApiPublicAuthWelcomeRoute
  ApiPublicBazikPayoutRoute: typeof ApiPublicBazikPayoutRoute
  ApiPublicDingconnectWebhookRoute: typeof ApiPublicDingconnectWebhookRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicSecurityAlertRoute: typeof ApiPublicSecurityAlertRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-enviar-dinero': {
      id: '/como-enviar-dinero'
      path: '/como-enviar-dinero'
      fullPath: '/como-enviar-dinero'
      preLoaderRoute: typeof ComoEnviarDineroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-dinero-a-haiti': {
      id: '/enviar-dinero-a-haiti'
      path: '/enviar-dinero-a-haiti'
      fullPath: '/enviar-dinero-a-haiti'
      preLoaderRoute: typeof EnviarDineroAHaitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moncash': {
      id: '/moncash'
      path: '/moncash'
      fullPath: '/moncash'
      preLoaderRoute: typeof MoncashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natcash': {
      id: '/natcash'
      path: '/natcash'
      fullPath: '/natcash'
      preLoaderRoute: typeof NatcashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-password': {
      id: '/restablecer-password'
      path: '/restablecer-password'
      fullPath: '/restablecer-password'
      preLoaderRoute: typeof RestablecerPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifas': {
      id: '/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof TarifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trader': {
      id: '/trader'
      path: '/trader'
      fullPath: '/trader'
      preLoaderRoute: typeof TraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usa-to-haiti': {
      id: '/usa-to-haiti'
      path: '/usa-to-haiti'
      fullPath: '/usa-to-haiti'
      preLoaderRoute: typeof UsaToHaitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/como-enviar-dinero': {
      id: '/$lang/como-enviar-dinero'
      path: '/$lang/como-enviar-dinero'
      fullPath: '/$lang/como-enviar-dinero'
      preLoaderRoute: typeof LangComoEnviarDineroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contacto': {
      id: '/$lang/contacto'
      path: '/$lang/contacto'
      fullPath: '/$lang/contacto'
      preLoaderRoute: typeof LangContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/enviar-dinero-a-haiti': {
      id: '/$lang/enviar-dinero-a-haiti'
      path: '/$lang/enviar-dinero-a-haiti'
      fullPath: '/$lang/enviar-dinero-a-haiti'
      preLoaderRoute: typeof LangEnviarDineroAHaitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/moncash': {
      id: '/$lang/moncash'
      path: '/$lang/moncash'
      fullPath: '/$lang/moncash'
      preLoaderRoute: typeof LangMoncashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/natcash': {
      id: '/$lang/natcash'
      path: '/$lang/natcash'
      fullPath: '/$lang/natcash'
      preLoaderRoute: typeof LangNatcashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/sobre-nosotros': {
      id: '/$lang/sobre-nosotros'
      path: '/$lang/sobre-nosotros'
      fullPath: '/$lang/sobre-nosotros'
      preLoaderRoute: typeof LangSobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/tarifas': {
      id: '/$lang/tarifas'
      path: '/$lang/tarifas'
      fullPath: '/$lang/tarifas'
      preLoaderRoute: typeof LangTarifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/trader': {
      id: '/$lang/trader'
      path: '/$lang/trader'
      fullPath: '/$lang/trader'
      preLoaderRoute: typeof LangTraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agente': {
      id: '/_authenticated/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AuthenticatedAgenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cripto': {
      id: '/_authenticated/cripto'
      path: '/cripto'
      fullPath: '/cripto'
      preLoaderRoute: typeof AuthenticatedCriptoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviar': {
      id: '/_authenticated/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof AuthenticatedEnviarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recargas': {
      id: '/_authenticated/recargas'
      path: '/recargas'
      fullPath: '/recargas'
      preLoaderRoute: typeof AuthenticatedRecargasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soporte': {
      id: '/_authenticated/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AuthenticatedSoporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transferencia/$id': {
      id: '/_authenticated/transferencia/$id'
      path: '/transferencia/$id'
      fullPath: '/transferencia/$id'
      preLoaderRoute: typeof AuthenticatedTransferenciaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/welcome': {
      id: '/api/public/auth/welcome'
      path: '/api/public/auth/welcome'
      fullPath: '/api/public/auth/welcome'
      preLoaderRoute: typeof ApiPublicAuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bazik/payout': {
      id: '/api/public/bazik/payout'
      path: '/api/public/bazik/payout'
      fullPath: '/api/public/bazik/payout'
      preLoaderRoute: typeof ApiPublicBazikPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dingconnect/webhook': {
      id: '/api/public/dingconnect/webhook'
      path: '/api/public/dingconnect/webhook'
      fullPath: '/api/public/dingconnect/webhook'
      preLoaderRoute: typeof ApiPublicDingconnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/security/alert': {
      id: '/api/public/security/alert'
      path: '/api/public/security/alert'
      fullPath: '/api/public/security/alert'
      preLoaderRoute: typeof ApiPublicSecurityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgenteRoute: typeof AuthenticatedAgenteRoute
  AuthenticatedCriptoRoute: typeof AuthenticatedCriptoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnviarRoute: typeof AuthenticatedEnviarRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRecargasRoute: typeof AuthenticatedRecargasRoute
  AuthenticatedSoporteRoute: typeof AuthenticatedSoporteRoute
  AuthenticatedTransferenciaIdRoute: typeof AuthenticatedTransferenciaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgenteRoute: AuthenticatedAgenteRoute,
  AuthenticatedCriptoRoute: AuthenticatedCriptoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnviarRoute: AuthenticatedEnviarRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRecargasRoute: AuthenticatedRecargasRoute,
  AuthenticatedSoporteRoute: AuthenticatedSoporteRoute,
  AuthenticatedTransferenciaIdRoute: AuthenticatedTransferenciaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoEnviarDineroRoute: ComoEnviarDineroRoute,
  ContactoRoute: ContactoRoute,
  EnviarDineroAHaitiRoute: EnviarDineroAHaitiRoute,
  FaqRoute: FaqRoute,
  MoncashRoute: MoncashRoute,
  NatcashRoute: NatcashRoute,
  PrivacidadRoute: PrivacidadRoute,
  RestablecerPasswordRoute: RestablecerPasswordRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TarifasRoute: TarifasRoute,
  TraderRoute: TraderRoute,
  UsaToHaitiRoute: UsaToHaitiRoute,
  LangComoEnviarDineroRoute: LangComoEnviarDineroRoute,
  LangContactoRoute: LangContactoRoute,
  LangEnviarDineroAHaitiRoute: LangEnviarDineroAHaitiRoute,
  LangMoncashRoute: LangMoncashRoute,
  LangNatcashRoute: LangNatcashRoute,
  LangSobreNosotrosRoute: LangSobreNosotrosRoute,
  LangTarifasRoute: LangTarifasRoute,
  LangTraderRoute: LangTraderRoute,
  LangIndexRoute: LangIndexRoute,
  ApiPublicAuthWelcomeRoute: ApiPublicAuthWelcomeRoute,
  ApiPublicBazikPayoutRoute: ApiPublicBazikPayoutRoute,
  ApiPublicDingconnectWebhookRoute: ApiPublicDingconnectWebhookRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicSecurityAlertRoute: ApiPublicSecurityAlertRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
